### PR TITLE
starting of clone work item type

### PR DESCRIPTION
**Pull request by danhellem**
For issue #13

### CODE REVIEW

**Comment by beugnen** [comment]
Hi,
I was googling and came across this.  Thanks for adding this feature.  How do I use azure-devops-process-cli?

**Comment by danhellem** [comment]
it's just a dotnet core command line app. Just install and run it :)

if you have any questions let me know

**Comment by beugnen** [comment]
Thanks I will :)

**Comment by rasheedalsheikh** [comment]
thanks for the awesome feature! is there an official eta for this to rollout?

**Pull request merged**
